### ISSUE TITLE
How to exclude assertJGen from gradle build cycle?

### ISSUE THREAD

**Issue by rmarinsky** [opengl-8080/assertjGen-gradle-plugin#10]

**Comment by opengl-8080** [comment]
`assertjGen` is embedded in build cycle staticaly.

**[AssertjGen.groovy](https://github.com/opengl-8080/assertjGen-gradle-plugin/blob/master/src/main/groovy/com/github/opengl8080/gradle/plugin/assertj/AssertjGen.groovy#L31)**

```groovy
project.task(type: JavaExec, dependsOn: ['assertjClean', 'compileJava'], 'assertjGen') {
...
project.compileTestJava.dependsOn('assertjGen')
```

`assertjClean` and `compileJava` -> `assertjGen` -> `compileTestJava`

If you want remove `assertjGen` from build cycle, you can remove `"assertjGen"` from `compileTestJava.dependsOn`.

**Example**

```groovy
compileTestJava.dependsOn.remove("assertjGen")
```

**Comment by rmarinsky** [comment]
Thanks)
