### ISSUE TITLE
Feature Request: option to include files outside of compile-configuration

### ISSUE THREAD

**Issue by michaelomann** [opengl-8080/assertjGen-gradle-plugin#11]
My project structure  defines multiple source sets (e.g. `main`, `common`, `api`). When a file is not located in the `main` source set it is ignored by the plugin.

Let assume the following build structure:
```
sourceSets {
    main {
        java {
            srcDirs {
                "src/main/java"
            }
        }
    }
   api {
        java {
            srcDirs {
                "src/api/java"
            }
        }
    }
   common {
        java {
            srcDirs {
                "src/common/java"
            }
        }
    }
}

```
So any files located in `src/api/java` or `src/common/java` are excluded and no assertions are 
generated. The reason seems to be the following line of code:

```
project.dependencies.add(configurationName, project.files(project.compileJava.destinationDir))
```

I would to nice to be able to define `configurations` in addition to `compileJava`, eg. `compileApiJava`, `compileCommonJava`,...

**Comment by opengl-8080** [comment]
Thank you your propose.

I added `assertjGenPreConfig`, and add `sourceSets` option in it.

Please set `sourceSets` like following.

**your build.gradle**

```groovy
apply plugin: 'java'

sourceSets {
    main {
        java {
            srcDirs {
                "src/main/java"
            }
        }
    }
   api {
        java {
            srcDirs {
                "src/api/java"
            }
        }
    }
   common {
        java {
            srcDirs {
                "src/common/java"
            }
        }
    }
}

ext {
    assertjGenPreConfig = [
        "sourceSets": ["main", "api", "common"]
    ]
}

apply: plugin 'com.github.opengl-BOBO.assertjGen'
```

Note you must declare `assertjGenPreConfig` and `sourceSets` before `apply: plugin 'com.github.opengl-BOBO.assertjGen'`.
Because, this plugin needs to read these options at loaded.

**Comment by michaelomann** [comment]
Thanks for adding the feature. 👍

Unfortunately I am having trouble resolving the dependency to version `1.1.5`. 

This is `build.gradle`:
```
buildscript {
    repositories {
        ...
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
       ...
        classpath "gradle.plugin.com.github.opengl-8080:assertjGen-gradle-plugin:1.1.5"
    }
}

apply plugin: "com.github.opengl-BOBO.assertjGen"
```

And this is the error I get:
```
   > Could not find gradle.plugin.com.github.opengl-8080:assertjGen-gradle-plugin:1.1.5.
     Searched in the following locations:
         ...
         https://plugins.gradle.org/m2/gradle/plugin/com/github/opengl-8080/assertjGen-gradle-plugin/1.1.5/assertjGen-gradle-plugin-1.1.5.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/github/opengl-8080/assertjGen-gradle-plugin/1.1.5/assertjGen-gradle-plugin-1.1.5.jar
```

Version `1.1.4` works fine. Maybe something went wrong while uploading the new artefact to the plugin registry?

**Comment by opengl-8080** [comment]
I'm sorry.
I can't understand what happened.

I tried to publish v1.1.6 (contents are same to 1.1.5).
Publishing task was completed successfully.

```
>gradle publishPlugins
:compileJava NO-SOURCE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:groovydoc
Trying to override old definition of task fileScanner
:publishPluginGroovyDocsJar
:publishPluginJar
:javadoc NO-SOURCE
:publishPluginJavaDocsJar
:publishPlugins
Publishing plugin com.github.opengl-BOBO.assertjGen version 1.1.6
Publishing artifact build/libs/assertjGen-gradle-plugin-1.1.6.jar
Publishing artifact build/libs/assertjGen-gradle-plugin-1.1.6-sources.jar
Publishing artifact build/libs/assertjGen-gradle-plugin-1.1.6-javadoc.jar
Publishing artifact build/libs/assertjGen-gradle-plugin-1.1.6-groovydoc.jar
Publishing artifact build/publish-generated-resources/pom.xml
Activating plugin com.github.opengl-BOBO.assertjGen version 1.1.6

BUILD SUCCESSFUL
```

However, I couldn't use it. I got a same error.

```
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find gradle.plugin.com.github.opengl-8080:assertjGen-gradle-plugin:1.1.6.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/com/github/opengl-8080/assertjGen-gradle-plugin/1.1.6/assertjGen-gradle-plugin-1.1.6.pom
         https://plugins.gradle.org/m2/gradle/plugin/com/github/opengl-8080/assertjGen-gradle-plugin/1.1.6/assertjGen-gradle-plugin-1.1.6.jar
     Required by:
         project :
```

I try to investigate this problem.

If you want to use this new feature, please git clone this project to your local machine, and execute `gradle jar` task.
You will get a jar file in the `build/libs` directory, and use it.

```groovy
buildscript {
    
    dependencies {
        classpath files("path/to/assertjGen-gradle-plugin-1.1.6.jar")
    }
}
```

**Comment by opengl-8080** [comment]
I resolved this problem.

Using too old `plugin-publish-plugin` plugin is a cause of this problem.
I update `plugin-publish-plugin` from `0.9.2` to `0.9.7`.

Please use `v1.1.7`.

**Comment by michaelomann** [comment]
Works now. Great job.

A few considerations:
The `plugins {...}` notation does not work in conjunction with this feature, because gradle does not allow any code before `plugins {...}`. 

```
plugins {
    id "com.github.opengl-BOBO.assertjGen" version "1.1.7"
}
```

Most people prefer this notation because it does not require any classpath dependencies.

Perhaps the plugin can be tweaked to load portions of the `assertjGenPreConfig` at execution time, not at configuration time.
