### ISSUE TITLE
plugin prevents overriding mavenCentral repository

### ISSUE THREAD

**Issue by waliferus** [opengl-8080/assertjGen-gradle-plugin#8]
The real issue is `mavenCentral` has a `.pom` for `javax.media:jai_core:1.1.3` but the `.jar` is missing[1]. The easy workaround when not using this plugin is to prepend a repository with a correct install. This is where this plugin, apparently due to explicitly re-adding `mavenCentral` as a repository, breaks builds. When the plugin is enabled, `gradle` reverts to using the broken `mavenCentral` repository even when my `build.gradle` places http://download.osgeo.org/webdav/geotools ahead of `mavenCentral`.

1. as described in https://stackoverflow.com/questions/26993105/i-get-an-error-downloading-javax-media-jai-core1-1-3-from-maven-central#26993223

**Comment by opengl-8080** [comment]
Thank you for your bug report.

I remove `mavenCentral()` configuration from this plugin.

Please configure `repositories` explicitly.

**build.gradle (example)**

```groovy
repositories {
    maven { url="http://download.osgeo.org/webdav/geotools" }
    mavenCentral() // Plugin uses 'assertj-assertions-generator' module. Therefore this is needed.
}
```

**Comment by waliferus** [comment]
Thank you! That fixed the issue.
